### ISSUE TITLE
Running on custom video sequences

### ISSUE THREAD

**Issue by aakash26** [t-taniai/FSF_CVPR2017_Demo#1]
Hi Authors,

For tunning the code on custom sequences, where should the camera calibrations be placed ?
Also is there a specific folder for left-subview and another one for right-subviews?

Regards
Aakash

**Comment by t-taniai** [comment]
Thanks for the question.

Please refer to a format provided in `/dataset/Custom'.
Specifically, 
- Place a sequence of left images in `/dataset/YOUR_DATA/left`.
- Place a sequence of right images in `/dataset/YOUR_DATA/right`.
- Place a text file at `\dataset\Custom\calib.txt` for camera calibration info.

The format of calib.txt basically follows that of KITTI's calibration data as follows.
```
P2: v1 v2 v3 v4 v5 v6 v7 v8 v9 v10 v11 v12
P3: v1 v2 v3 v4 v5 v6 v7 v8 v9 v10 v11 v12
```
Here, two sets of twelve values represent elements of 3x4 calibration matrices for left (P2) and right (P3) views, ie,
```
          [ v1  v2  v3  v4 ]
K[R|t] =  [ v5  v6  v7  v8 ]
          [ v9 v10 v11 v12 ].
```
For each camera, K is 3x3 intrinsic parameter matrix, R and t are a 3D rotation matrix and translation vector (extrinsic parameters). Typically, the left view is chosen as a reference camera (left viewpoint is chosen as the origin of the 3D coordinate system), so its R is often set to the identity matrix and t is set to the zero vector.
